#!/bin/bash
adb shell pm uninstall -k --user 0 com.coloros.assistantscreen
adb shell pm uninstall -k --user 0 com.heytap.browser
adb shell pm uninstall -k --user 0 com.google.android.calendar
adb shell pm uninstall -k --user 0 com.heytap.cloud
adb shell pm uninstall -k --user 0 com.google.android.apps.googleassistant
adb shell pm uninstall -k --user 0 com.google.android.contacts
adb shell pm uninstall -k --user 0 com.google.ar.lens
adb shell pm uninstall -k --user 0 com.oplus.omoji
adb shell pm uninstall -k --user 0 com.coloros.activation
adb shell pm uninstall -k --user 0 com.google.android.apps.photos
adb shell pm uninstall -k --user 0 com.redteamobile.roaming
adb shell pm uninstall -k --user 0 com.oppo.quicksearchbox
adb shell pm uninstall -k --user 0 com.google.android.dialer
adb shell pm uninstall -k --user 0 com.google.android.apps.nbu.files
adb shell pm uninstall -k --user 0 com.google.android.apps.healthdata
adb shell pm uninstall -k --user 0 com.oplus.themestore
adb shell pm uninstall -k --user 0 com.google.android.apps.messaging
adb shell pm uninstall -k --user 0 com.oneplus.membership
adb shell pm uninstall -k --user 0 android.autoinstalls.config.oneplus
adb shell pm uninstall -k --user 0 com.google.ar.core
adb shell pm uninstall -k --user 0 com.android.chrome
adb shell pm uninstall -k --user 0 com.android.providers.partnerbookmarks
adb shell pm uninstall -k --user 0 com.android.email.partnerprovider
adb shell pm uninstall -k --user 0 com.google.android.gms.location.history
adb shell pm uninstall -k --user 0 com.oplus.interconnectcollectkit
adb shell pm uninstall -k --user 0 com.heytap.mcs
adb shell pm uninstall -k --user 0 com.google.android.tts
adb shell pm uninstall -k --user 0 com.google.android.accessibility.switchaccess
adb shell pm uninstall -k --user 0 com.google.android.marvin.talkback
adb shell pm uninstall -k --user 0 com.google.android.youtube
adb shell pm uninstall -k --user 0 com.google.android.printservice.recommendation
adb shell pm uninstall -k --user 0 com.google.android.feedback
adb shell pm uninstall -k --user 0 com.google.android.projection.gearhead
adb shell pm uninstall -k --user 0 com.google.android.gms.supervision
adb shell pm uninstall -k --user 0 com.google.android.apps.restore
adb shell pm uninstall -k --user 0 com.google.android.googlequicksearchbox
adb shell pm uninstall -k --user 0 com.google.android.apps.wellbeing
adb shell pm uninstall -k --user 0 com.coloros.systemclone
adb shell pm uninstall -k --user 0 com.android.hotwordenrollment.okgoogle
adb shell pm uninstall -k --user 0 com.android.hotwordenrollment.xgoogle
adb shell pm uninstall -k --user 0 com.oplus.aod
adb shell pm uninstall -k --user 0 com.coloros.childrenspace
adb shell pm uninstall -k --user 0 com.coloros.floatassistant
adb shell pm uninstall -k --user 0 com.coloros.operationManual
adb shell pm uninstall -k --user 0 com.oplus.securitykeyboard
adb shell pm uninstall -k --user 0 net.oneplus.weather
adb shell pm uninstall -k --user 0 com.coloros.weather.service
adb shell pm uninstall -k --user 0 com.oplus.portrait
adb shell pm uninstall -k --user 0 com.coloros.scenemode
adb shell pm uninstall -k --user 0 com.coloros.smartsidebar
adb shell pm uninstall -k --user 0 com.oplus.viewtalk
adb shell pm uninstall -k --user 0 com.oplus.statistics.rom
adb shell pm uninstall -k --user 0 com.oplus.games
adb shell pm uninstall -k --user 0 com.oplus.cast
adb shell pm uninstall -k --user 0 com.oneplus.account
adb shell pm uninstall -k --user 0 com.microsoft.appmanager
adb shell pm uninstall -k --user 0 com.oplus.metis
adb shell pm uninstall -k --user 0 com.oplus.onet
adb shell pm uninstall -k --user 0 com.google.android.partnersetup 
adb shell pm uninstall -k --user 0 com.oplus.linker
adb shell pm uninstall -k --user 0 com.oplus.sos
adb shell pm uninstall -k --user 0 com.oplus.wallpapers
adb shell pm uninstall -k --user 0 com.android.dreams.basic
adb shell pm uninstall -k --user 0 com.android.bookmarkprovider
adb shell pm uninstall -k --user 0 com.android.backupconfirm
adb shell pm uninstall -k --user 0 com.android.calllogbackup
adb shell pm uninstall -k --user 0 com.android.apps.tag
adb shell pm uninstall -k --user 0 com.qualcomm.atfwd
adb shell pm uninstall -k --user 0 com.qualcomm.atfwd2
adb shell pm uninstall -k --user 0 com.oplus.crashbox
adb shell pm uninstall -k --user 0 com.android.htmlviewer
adb shell pm uninstall -k --user 0 com.oplus.logkit
adb shell pm uninstall -k --user 0 com.oplus.multiapp
adb shell pm uninstall -k --user 0 com.android.printspooler
adb shell pm uninstall -k --user 0 com.oplus.sauhelper
adb shell pm uninstall -k --user 0 com.android.stk
adb shell pm uninstall -k --user 0 com.android.systemui.accessibility.accessibilitymenu
adb shell pm uninstall -k --user 0 com.android.bips
adb shell pm uninstall -k --user 0 com.oplus.deepthinker
adb shell pm uninstall -k --user 0 com.android.systemui.plugin.globalactions.wallet
adb shell pm uninstall -k --user 0 com.google.android.adservices.api
adb shell pm uninstall -k --user 0 com.oplus.aiunit
adb shell pm uninstall -k --user 0 com.aiunit.aon
adb shell pm uninstall -k --user 0 com.coloros.ocrscanner
adb shell pm uninstall -k --user 0 com.oplus.synergy
adb shell pm uninstall -k --user 0 com.android.wallpaper.livepicker
adb shell pm uninstall -k --user 0 com.oplus.onetrace
adb shell pm uninstall -k --user 0 com.coloros.colordirectservice
